
# core_constants.py, Copyright (c) 2019, Phenome Project - Nicholas Saparoff <nick.saparoff@gmail.com>

# some variables to use for unit tests
CONST_MODEL_NAME_TO_TEST = 'ROOT_SENSOR'

CONST_MODEL_CLASSTYPE_TO_TEST_KEY_GENERIC_DEVICE = 'GENERIC_DEVICE'
CONST_MODEL_CLASSTYPE_TO_TEST_KEY = 'ENVIRONMENT_SENSOR'
CONST_MODEL_PROP_TO_TEST_KEY = 'health'
CONST_MODEL_CLASSTYPE_DEFAULT_PROPERTY_TO_TEST = 'temp_error'
CONST_MODEL_CLASSTYPE_TO_TEST_VALUE = 2

# Used in core_001_model_test and many API call tests in core_002_api_test, and core_005_actionmodel tests
CONST_TEST_MACADDRESS = 'AA:BB:CC:DD:EE:FF'
CONST_TEST_IPADDRESS = '1.0.0.0'

CONST_TEST_MACADDRESS_2 = 'AA:BB:CC:DD:EE:00'
CONST_TEST_IPADDRESS_2 = '1.0.0.1'


# Used for testing ADD and DELETE only
CONST_TEST_MACADDRESS_ADD_DELETE_ONLY = 'FF:00:00:00:00:FF'
CONST_TEST_IPADDRESS_ADD_DELETE_ONLY = '1.0.0.1'

CONST_TEST_MODEL_TAG = 'TEST_MODEL'
CONST_TEST_PROPERTY_VALUE_DEFAULT = 12345
CONST_TEST_PROPERTY_VALUE = 45678
CONST_TEST_PROPERTY_MODEL_NAME = 'test_property_model'
CONST_TEST_PROPERTY_MODEL_NAME_REQUIRED = 'test_property_model_required_property'

CONST_BASE_URL = "http://localhost:5000"

