routes = {
    '{"command": "stats"}': {
      "IP": "10.5.78.1",
      "STATS": [
        {
          "CGMiner": "4.9.0",
          "CompileTime": "Tue Apr 23 13:15:06 CST 2019",
          "Miner": "9.0.0.5",
          "Type": "Antminer Z11"
        },
        {
          "Calls": 0,
          "Device Hardware%": 0.0,
          "Elapsed": 405302,
          "GHS 5s": "151.38",
          "GHS av": 139.82,
          "ID": "ZCASH0",
          "Max": 0.0,
          "Min": 99999999.0,
          "STATS": 0,
          "Wait": 0.0,
          "chain_acn1": 3,
          "chain_acn2": 3,
          "chain_acn3": 3,
          "chain_acn4": 0,
          "chain_acs1": " ooo",
          "chain_acs2": " ooo",
          "chain_acs3": " ooo",
          "chain_acs4": "",
          "chain_hw1": 5185,
          "chain_hw2": 4796,
          "chain_hw3": 56,
          "chain_hw4": 0,
          "chain_rate1": "48.49",
          "chain_rate2": "43.25",
          "chain_rate3": "59.63",
          "chain_rate4": "",
          "fan1": 3960,
          "fan2": 3960,
          "fan3": 0,
          "fan4": 0,
          "fan5": 0,
          "fan6": 0,
          "fan_num": 2,
          "frequency1": 729,
          "frequency2": 731,
          "frequency3": 731,
          "frequency4": 0,
          "miner_count": 3,
          "no_matching_work": 0,
          "temp1": 46,
          "temp2": 49,
          "temp2_1": 64,
          "temp2_2": 70,
          "temp2_3": 62,
          "temp2_4": 0,
          "temp3": 44,
          "temp4": 0,
          "temp_max": 49,
          "temp_num": 3
        }
      ],
      "STATUS": [
        {
          "Code": 70,
          "Description": "cgminer 4.9.0",
          "Msg": "CGMiner stats",
          "STATUS": "S",
          "When": 1575579312
        }
      ],
      "id": 1
    },
    '{"command": "pools"}': {
      "IP": "10.5.78.1",
      "POOLS": [
        {
          "Accepted": 589364,
          "Best Share": 0,
          "Diff": "16",
          "Diff1 Shares": 0,
          "Difficulty Accepted": 9429824.0,
          "Difficulty Rejected": 7920.0,
          "Difficulty Stale": 112.0,
          "Discarded": 212384,
          "Get Failures": 4,
          "Getworks": 5953,
          "Has GBT": False,
          "Has Stratum": True,
          "Last Share Difficulty": 16.0,
          "Last Share Time": "0:00:00",
          "Long Poll": "N",
          "POOL": 0,
          "Pool Rejected%": 0.0839,
          "Pool Stale%": 0.0012,
          "Priority": 0,
          "Proxy": "",
          "Proxy Type": "",
          "Quota": 1,
          "Rejected": 495,
          "Remote Failures": 1,
          "Stale": 7,
          "Status": "Alive",
          "Stratum Active": True,
          "Stratum URL": "us1-zcash.flypool.org",
          "URL": "stratum+tcp://us1-zcash.flypool.org:3333",
          "User": "t1b74Hwwv5Z8duSEoSwB6FeRMp56kAAAAA.worker1"
        },
        {
          "Accepted": 0,
          "Best Share": 0,
          "Diff": "",
          "Diff1 Shares": 0,
          "Difficulty Accepted": 0.0,
          "Difficulty Rejected": 0.0,
          "Difficulty Stale": 0.0,
          "Discarded": 0,
          "Get Failures": 0,
          "Getworks": 1,
          "Has GBT": False,
          "Has Stratum": True,
          "Last Share Difficulty": 0.0,
          "Last Share Time": "0",
          "Long Poll": "N",
          "POOL": 1,
          "Pool Rejected%": 0.0,
          "Pool Stale%": 0.0,
          "Priority": 1,
          "Proxy": "",
          "Proxy Type": "",
          "Quota": 1,
          "Rejected": 0,
          "Remote Failures": 0,
          "Stale": 0,
          "Status": "Alive",
          "Stratum Active": False,
          "Stratum URL": "",
          "URL": "stratum+tcp://equihash.f2pool.com:5100",
          "User": "necromancer2112.worker41"
        },
        {
          "Accepted": 0,
          "Best Share": 0,
          "Diff": "",
          "Diff1 Shares": 0,
          "Difficulty Accepted": 0.0,
          "Difficulty Rejected": 0.0,
          "Difficulty Stale": 0.0,
          "Discarded": 0,
          "Get Failures": 0,
          "Getworks": 1,
          "Has GBT": False,
          "Has Stratum": True,
          "Last Share Difficulty": 0.0,
          "Last Share Time": "0",
          "Long Poll": "N",
          "POOL": 2,
          "Pool Rejected%": 0.0,
          "Pool Stale%": 0.0,
          "Priority": 2,
          "Proxy": "",
          "Proxy Type": "",
          "Quota": 1,
          "Rejected": 0,
          "Remote Failures": 0,
          "Stale": 0,
          "Status": "Alive",
          "Stratum Active": False,
          "Stratum URL": "",
          "URL": "stratum+tcp://us-east.zec.slushpool.com:4444",
          "User": "necromancer2112a.worker41"
        }
      ],
      "STATUS": [
        {
          "Code": 7,
          "Description": "cgminer 4.9.0",
          "Msg": "3 Pool(s)",
          "STATUS": "S",
          "When": 1575579288
        }
      ],
      "id": 1
    },
    '{"command": "summary"}': {
      "IP": "10.5.78.1",
      "STATUS": [
        {
          "Code": 11,
          "Description": "cgminer 4.9.0",
          "Msg": "Summary",
          "STATUS": "S",
          "When": 1575579245
        }
      ],
      "SUMMARY": [
        {
          "Accepted": 589298,
          "Best Share": 0,
          "Device Hardware%": 0.0,
          "Device Rejected%": 0.0839,
          "Difficulty Accepted": 9428768.0,
          "Difficulty Rejected": 7920.0,
          "Difficulty Stale": 112.0,
          "Discarded": 212361,
          "Elapsed": 405235,
          "Found Blocks": 0,
          "GHS 5s": "130.41",
          "GHS av": 139.82,
          "Get Failures": 4,
          "Getworks": 5954,
          "Hardware Errors": 0,
          "Last getwork": 1575579244,
          "Local Work": 348938,
          "Network Blocks": 1,
          "Pool Rejected%": 0.0839,
          "Pool Stale%": 0.0012,
          "Rejected": 495,
          "Remote Failures": 1,
          "Stale": 7,
          "Total MH": 56660172128.0,
          "Utility": 87.25,
          "Work Utility": 1397.23
        }
      ],
      "id": 1
    }
}




